#ifndef COMPILE_H
#define COMPILE_H


#define NUMBER_OF_TOKENS 45
#define MAX_TOKEN_LENGTH 9


#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <stdint.h>
#include "../libraries/vector.h"
#include "../libraries/datastructures.h"
#include "../libraries/static hashmap.h"
#include "../libraries/dynamic string.h"
extern const char validTokens[NUMBER_OF_TOKENS][MAX_TOKEN_LENGTH];


typedef enum VALID_TOKEN_ENUM {

    EOF_TOKEN = -1,
    INT_IMMEDIATE = -2,
    FLOAT_IMMEDIATE = -3,
    CHAR_IMMEDIATE = -4,


    USER_STRING = -5,


    INVALID_TOKEN = 0,
    TOK_SET = 1,
    TOK_VAR_DECL = 2,
    TOK_FUN_CALL = 3,
    TOK_FUN_DECL = 4,


    TOK_IF = 5,
    TOK_GTO = 6,
    TOK_LBL = 7,
    TOK_END_FN = 8,
    TOK_ENDIF = 9,


    TOK_INT = 10,
    TOK_FLT = 11,
    TOK_CHR = 12,
    TOK_PTR = 13,
    TOK_EQUALS_ASSIGNMENT = 14,


    TOK_ADD = 15,
    TOK_SUB = 16,
    TOK_MUL = 17,
    TOK_DIV = 18,
    TOK_MOD = 19,


    TOK_OR = 20,
    TOK_AND = 21,
    TOK_EQUAL_TO = 22,
    TOK_NOT_EQUAL_TO = 23,
    TOK_GREATER_EQUAL_TO = 24,


    TOK_LESS_EQUAL_TO = 25,
    TOK_GREATER_TO = 26,
    TOK_LESS_TO = 27,
    TOK_DEREFERENCE_PTR = 28,
    TOK_ALLOCATE = 29,


    TOK_FREE = 30,
    TOK_SIZEOF = 31,
    TOK_COMMENT = 32,
    TOK_OPEN_ANGLE = 33,
    TOK_CLOSE_ANGLE = 34,


    TOK_OPEN_SQUAER = 35,
    TOK_CLOSE_SQUARE = 36,
    TOK_OPEN_PAREN = 37,
    TOK_CLOSE_PAREN = 38,
    TOK_OPEN_CURLEY = 39,


    TOK_CLOSE_CURLEY = 40,
    TOK_COMMA = 41,
    TOK_DOT = 42,
    TOK_SEMICOLEN = 43,
    TOK_SINGLE_QUOTE = 44,


} VALID_TOKEN_ENUM;




typedef struct Token {

    VALID_TOKEN_ENUM tokenEnum;

    //Immediates and variables
    union {
        DynamicString userString;  //User string (func name, variable, etc - parser must determine based on context)

        char charImmediate;        //Used if immediate char 'f'
        int intImmediate;          //Used for immediate int '3'
        float floatImmediate;      //Used for immediate float '3.32'
    };

} Token;




#endif //COMPILE_H

//NOTE: Generated by python script



