#ifndef COMPILE_H
#define COMPILE_H


#define NUMBER_OF_TOKENS 39
#define MAX_TOKEN_LENGTH 9


#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <stdint.h>
#include "../libraries/vector.h"
#include "../libraries/datastructures.h"
#include "../libraries/static hashmap.h"
#include "../libraries/dynamic string.h"
extern const char validTokens[NUMBER_OF_TOKENS][MAX_TOKEN_LENGTH];


typedef enum VALID_TOKEN_ENUM {

    EOF_TOKEN = -1,
    INT_IMMEDIATE = -2,
    FLOAT_IMMEDIATE = -3,
    CHAR_IMMEDIATE = -4,


    USER_STRING = -5,


    INVALID_TOKEN = 0,
    TOK_INT = 1,
    TOK_FLT = 2,
    TOK_CHR = 3,
    TOK_PTR = 4,


    TOK_EQUALS_ASSIGNMENT = 5,
    TOK_ADD = 6,
    TOK_SUB = 7,
    TOK_MUL = 8,
    TOK_DIV = 9,


    TOK_MOD = 10,
    TOK_OR = 11,
    TOK_AND = 12,
    TOK_EQUAL_TO = 13,
    TOK_NOT_EQUAL_TO = 14,


    TOK_GREATER_EQUAL_TO = 15,
    TOK_LESS_EQUAL_TO = 16,
    TOK_GREATER_TO = 17,
    TOK_LESS_TO = 18,
    TOK_IF = 19,


    TOK_GTO = 20,
    TOK_LBL = 21,
    TOK_FN = 22,
    TOK_RET = 23,
    TOK_ALLOCATE = 24,


    TOK_FREE = 25,
    TOK_SIZEOF = 26,
    TOK_OPEN_ANGLE = 27,
    TOK_CLOSE_ANGLE = 28,
    TOK_OPEN_SQUAER = 29,


    TOK_CLOSE_SQUARE = 30,
    TOK_OPEN_PAREN = 31,
    TOK_CLOSE_PAREN = 32,
    TOK_OPEN_CURLEY = 33,
    TOK_CLOSE_CURLEY = 34,


    TOK_COMMA = 35,
    TOK_DOT = 36,
    TOK_SEMICOLEN = 37,
    TOK_SINGLE_QUOTE = 38,


} VALID_TOKEN_ENUM;




typedef struct Token {

    VALID_TOKEN_ENUM tokenEnum;

    //Immediates and variables
    union {
        DynamicString userString;  //User string (func name, variable, etc - parser must determine based on context)

        char charImmediate;        //Used if immediate char 'f'
        int intImmediate;          //Used for immediate int '3'
        float floatImmediate;      //Used for immediate float '3.32'
    };

} Token;




#endif //COMPILE_H

//NOTE: Generated by python script



