#include "compiler data.h"


const char validTokens[NUMBER_OF_TOKENS][MAX_TOKEN_LENGTH] = {




    "invalid","set","dec","cal","fnc",



    "if","gto","lbl","endfn","endif",



    "int","flt","chr","@","=",



    "+","-","*","/","\%",



    "||","&&","==","!=",">=",



    "<=",">>","<<","?","allocate",



    "free","sizeof","//","<",">",



    "[","]","(",")","{",



    "}",",",".","'",

};

//NOTE: Generated by python script



