#include "compiler data.h++"


const char validTokens[NUMBER_OF_TOKENS][MAX_TOKEN_LENGTH] = {




    "invalid","set","dec","cal","fnc",



    "int","=","+","-","*",



    "/","\%","<<","==","<=",



    "if","endif","goto","label",

};

//NOTE: Generated by python script



