#include "compiler data.h++"


const char validTokens[NUMBER_OF_TOKENS][MAX_TOKEN_LENGTH] = {




    "invalid","set","dec","if","endif",



    "goto","label","=","+=","-=",



    "*=","/=","\%=","<<","==",



    "<=","output",

};

//NOTE: Generated by python script



