#include "./compiler data.h"


const char validTokens[NUMBER_OF_TOKENS][MAX_TOKEN_LENGTH] = {




    "usr_str","invalid","int","flt","chr",



    "@","+","-","*","/",



    "%%","||","&&","==","!=",



    ">=","<=",">>","<<","if",



    "gto","lbl","fn","ret","allocate",



    "free","sizeof","//","<",">",



    "[","]","(",")","{",



    "}",",",".",";",

};

//NOTE: Generated by python script



